tasks/urls.py
from django.urls import path

from tasks.views import (
    Index,
    TaskTypesListView,
    TaskTypesCreateView,
    TaskTypesUpdateView,
    TaskTypesDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    TasksListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerPositionUpdateView,
    WorkerDeleteView,
    toggle_complete_to_task,
)

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("task-types/", TaskTypesListView.as_view(), name="task-type-list"),
    path(
        "task-types/create/",
        TaskTypesCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypesUpdateView.as_view(),
        name="task-type-update"
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypesDeleteView.as_view(),
        name="task-type-delete"
    ),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete"
    ),
    path("tasks/", TasksListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
         name="task-delete"
    ),
    path(
        "tasks/<int:pk>/toggle-complete/",
        toggle_complete_to_task,
        name="toggle-task-complete"
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path(
        "workers/<int:pk>/update/",
        WorkerPositionUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
]

app_name = "tasks"

tasks/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(Position, on_delete=models.CASCADE)

    class Meta:
        ordering = ["position", "last_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Task(models.Model):
    PRIORITY_CHOICES = [
        ("low", "Low"),
        ("medium", "Medium"),
        ("high", "High"),
        ("urgent", "Urgent")
    ]

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=255, choices=PRIORITY_CHOICES)
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(Worker, related_name="tasks")

    class Meta:
        ordering = ["deadline", "priority"]

    def __str__(self):
        return self.name

tasks/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Task, Worker


class TaskForm(forms.ModelForm):
    name = forms.CharField(
        max_length=255,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Enter task name"})
    )
    description = forms.CharField(
        label="",
        widget=forms.Textarea(
            attrs={"rows": 5, "placeholder": "Enter task description"})
    )
    deadline = forms.DateTimeField(
        label="",
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"})
    )
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label=""
    )

    class Meta:
        model = Task
        fields = [
            "name",
            "description",
            "task_type",
            "priority",
            "deadline",
            "assignees"
        ]
        labels = {
            "task_type": "",
            "priority": "",
        }


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"})
    )


class WorkerCreateForm(UserCreationForm):
    first_name = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Enter first name"})
    )
    last_name = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Enter last name"})
    )
    username = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Enter username"})
    )
    email = forms.EmailField(
        label="",
        widget=forms.EmailInput(attrs={"placeholder": "Enter email"})
    )
    password1 = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={"placeholder": "Enter password"}),
    )
    password2 = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm password"}),
    )

    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
            "position",
        )

        labels = {
            "position": ""
        }


class WorkerPositionUpdateForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = ["position"]

        labels = {
            "position": ""
        }


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"})
    )


class TaskTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"})
    )


class PositionSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"})
    )

tasks/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import TemplateView

from tasks.forms import (
    TaskForm,
    WorkerCreateForm,
    WorkerPositionUpdateForm,
    TaskSearchForm,
    WorkerSearchForm,
    PositionSearchForm
)
from tasks.models import Task, Worker, TaskType, Position


class Index(LoginRequiredMixin, TemplateView):
    template_name = "tasks/index.html"

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context["num_tasks"] = Task.objects.count()
        context["num_workers"] = Worker.objects.count()
        context["num_task_types"] = TaskType.objects.count()
        context["num_positions"] = Position.objects.count()
        context["pending_tasks"] = Task.objects.filter(
            is_completed=False
        ).order_by("deadline", "-priority")[:7]
        return context


class TaskTypesListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    context_object_name = "task_type_list"
    template_name = "tasks/task_type_list.html"
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super(TaskTypesListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TaskSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = TaskType.objects.all()
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskTypesCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    template_name = "tasks/task_type_form.html"
    success_url = reverse_lazy("tasks:task-types-list")


class TaskTypesUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    template_name = "tasks/task_type_form.html"
    success_url = reverse_lazy("tasks:task-types-list")


class TaskTypesDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    template_name = "tasks/task_type_confirm_delete.html"
    success_url = reverse_lazy("tasks:task-types-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    context_object_name = "position_list"
    template_name = "tasks/position_list.html"
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = PositionSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Position.objects.all()
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    template_name = "tasks/position_form.html"
    success_url = reverse_lazy("tasks:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    template_name = "tasks/position_form.html"
    success_url = reverse_lazy("tasks:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    template_name = "tasks/position_confirm_delete.html"
    success_url = reverse_lazy("tasks:position-list")


class TasksListView(LoginRequiredMixin, generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "tasks/task_list.html"
    paginate_by = 9

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TasksListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TaskSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Task.objects.all()
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    template_name = "tasks/task_detail.html"


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/task_form.html"
    success_url = reverse_lazy("tasks:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/task_form.html"

    def get_success_url(self):
        return reverse_lazy('tasks:task-detail', kwargs={'pk': self.object.pk})


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:task-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    context_object_name = "worker_list"
    template_name = "tasks/worker_list.html"
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = WorkerSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Worker.objects.all()
        form = WorkerSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"])
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = get_user_model()
    template_name = "tasks/worker_detail.html"

    def get_context_data(self, **kwargs):
        context = super(WorkerDetailView, self).get_context_data(**kwargs)
        context["completed_tasks"] = self.object.tasks.filter(
            is_completed=True).count()
        return context


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreateForm
    template_name = "tasks/worker_create_form.html"
    success_url = reverse_lazy("tasks:worker-list")


class WorkerPositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerPositionUpdateForm
    template_name = "tasks/worker_update_form.html"

    def get_success_url(self):
        return reverse_lazy(
            'tasks:worker-detail', kwargs={'pk': self.object.pk}
        )


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("tasks:worker-list")


@login_required
def toggle_complete_to_task(request, pk):
    task = Task.objects.get(pk=pk)
    task.is_completed = not task.is_completed
    task.save()
    return HttpResponseRedirect(reverse_lazy("tasks:task-detail", args=[pk]))

templates/tasks/position_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="row mt-4">
    <div class="col-12">
      <div class="card mb-4">
        <div class="card-header pb-0">
          <div class="row align-items-center">
            <div class="col">
              <h5 class="mb-0">Delete Position</h5>
              <p class="text-sm text-muted mb-0">
                Are you sure you want to delete this position?
              </p>
            </div>
            <div class="col text-end">
              <a href="{% url 'tasks:position-list' %}" class="btn btn-sm btn-outline-secondary">
                <i class="fas fa-arrow-left me-2"></i>Back to Positions
              </a>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="alert alert-warning" role="alert">
            <div class="d-flex text-white">
              <div class="pe-3">
                <i class="fas fa-exclamation-triangle fa-2x"></i>
              </div>
              <div>
                <h6 class="alert-heading mb-1">Warning</h6>
                <p class="mb-0">
                  You are about to delete position
                  "<strong>{{ position.name }}</strong>". This action cannot be undone.
                </p>
              </div>
            </div>
          </div>

          <div class="card shadow-none border mb-4">
            <div class="card-body">
              <h6 class="text-uppercase text-xs font-weight-bolder opacity-7 mb-3">
                Position Details
              </h6>
              <div class="row g-3">
                <div class="col-md-6">
                  <p class="text-sm mb-1">
                    <strong>Name:</strong> {{ position.name }}
                  </p>
                </div>
              </div>
            </div>
          </div>

          <form method="post">
            {% csrf_token %}
            <div class="d-flex justify-content-start gap-2">
              <a href="{% url 'tasks:position-list' %}" class="btn btn-outline-secondary">
                <i class="fas fa-times me-2"></i>Cancel
              </a>
              <button type="submit" class="btn btn-danger">
                <i class="fas fa-trash me-2"></i>Delete Position
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/position_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="row mt-4">
    <div class="col-12">
      <h3 class="mb-3">Positions</h3>
      <div class="card mb-4">
        <div class="card-header pb-0">
          <div class="row align-items-stretch">
            <div class="col-md-8 d-flex">
              <form method="get" class="d-flex w-100">
                <div class="position-relative w-100">
                  {{ search_form.name|as_crispy_field }}
                </div>
                <button type="submit" class="btn btn-primary ms-2 py-0">
                  Search
                </button>
              </form>
            </div>
            <div class="col-md-4 d-flex justify-content-end align-items-stretch">
              <a href="{% url 'tasks:position-create' %}"
                 class="btn btn-sm btn-primary text-center py-2"
                 style="line-height: 1.9; display: inline-block;">
                <i class="fas fa-plus me-2"></i>
                Create Position
              </a>
            </div>
          </div>
        </div>
        <div class="card-body px-0 pt-0 pb-2">
          <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
              <thead>
              <tr>
                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 w-100">
                  Position
                </th>
                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                  Update
                </th>
                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                  Delete
                </th>
              </tr>
              </thead>
              <tbody>
              {% for position in position_list %}
                <tr>
                  <td>
                    <div class="d-flex px-3 py-1">
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="mb-0 text-sm">
                          {{ position.name }}
                        </h6>
                      </div>
                    </div>
                  </td>
                  <td class="align-middle text-center text-sm">
                    <div class="d-flex flex-column justify-content-center">
                      <a href="{% url 'tasks:position-update' pk=position.id %}"
                         class="btn btn-sm btn-outline-primary d-block mx-auto">
                        <i class="fas fa-edit me-2"></i>
                        Update
                      </a>
                    </div>
                  </td>
                  <td class="align-middle text-center text-sm">
                    <div class="d-flex flex-column justify-content-center">
                      <a href="{% url 'tasks:position-delete' pk=position.id %}"
                         class="btn btn-sm btn-outline-primary d-block mx-auto">
                        <i class="fas fa-trash me-2"></i>
                        Delete
                      </a>
                    </div>
                  </td>
                  {% empty %}
                <tr>
                  <td colspan="5" class="text-center py-4">
                    <p class="text-sm mb-0">No positions found</p>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/task_detail.html
{% extends "base.html" %}
{% load get_initials %}
{% load priority_badge %}

{% block content %}
  <div class="row mt-4">
    <div class="col-12">
      <div class="card mb-4">
        <div class="card-header pb-0">
          <div class="row align-items-center">
            <div class="col">
              <a href="{% url 'tasks:task-list' %}"
                 class="btn btn-sm btn-outline-secondary">
                <i class="fas fa-arrow-left me-2"></i>
                Back to Tasks
              </a>
            </div>
            <div class="col text-end">
              <div class="d-flex align-items-center justify-content-end gap-2">
                <a href="{% url 'tasks:task-update' pk=task.id %}"
                   class="btn btn-sm btn-primary">
                  <i class="fas fa-edit me-2"></i>
                  Edit Task
                </a>
                <a href="{% url 'tasks:task-delete' pk=task.id %}"
                   class="btn btn-sm btn-danger">
                  <i class="fas fa-trash me-2"></i>
                  Delete Task
                </a>
              </div>
            </div>
          </div>
        </div>

        <div class="card-body pt-4">
          <div class="row">
            <div class="col-lg-8">
              <div class="card shadow-none border mb-4">
                <div class="card-body">
                  <h5 class="mb-1">{{ task.name }}</h5>
                  <p class="text-sm text-muted mb-3">
                    <i class="fas fa-tag me-2"></i>
                    {{ task.task_type }}
                  </p>

                  <div class="mb-4">
                    <h6 class="text-uppercase text-xs font-weight-bolder opacity-7">
                      Description
                    </h6>
                    <p class="text-sm mb-0">
                      {{ task.description|default:"No description provided" }}
                    </p>
                  </div>

                  <div class="row g-3">
                    <div class="col-md-4">
                      <h6 class="text-uppercase text-xs font-weight-bolder opacity-7">
                        Priority</h6>
                      <span
                          class="badge bg-gradient-{{ task.priority|priority_badge }}">
                      {{ task.priority }}
                      </span>
                    </div>
                    <div class="col-md-4">
                      <h6 class="text-uppercase text-xs font-weight-bolder opacity-7">
                        Status
                      </h6>
                      <span
                          class="badge bg-gradient-{{ task.is_completed|yesno:'success,warning' }}">
                      {{ task.is_completed|yesno:'Completed,Pending' }}
                      </span>
                    </div>
                    <div class="col-md-4">
                      <h6 class="text-uppercase text-xs font-weight-bolder opacity-7">
                        Deadline
                      </h6>
                      <div class="d-flex align-items-center">
                        <i class="fas fa-calendar-alt text-primary me-2"></i>
                        <div>
                          <p class="text-sm mb-0">{{ task.deadline|date:"M d, Y" }}
                            <span class="text-xs text-secondary mb-0">
                              {{ task.deadline|date:"g:i A" }}
                            </span>
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="text-start mt-5">
                    <a class="btn btn-{{ task.is_completed|yesno:"primary,success" }}"
                       href="{% url 'tasks:toggle-task-complete' pk=task.id %}">
                      {% if task.is_completed %}
                        <i class="fas fa-times me-1"></i>
                        <span>Mark Incomplete</span>
                      {% else %}
                        <i class="fas fa-check me-1"></i>
                        <span>Mark Complete</span>
                      {% endif %}
                    </a>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-lg-4">
              <div class="card shadow-none border">
                <div class="card-body">
                  <div
                      class="d-flex justify-content-between align-items-center mb-3">
                    <h6 class="text-uppercase text-xs font-weight-bolder opacity-7 mb-0">
                      Assignees
                    </h6>
                  </div>
                  {% for assignee in task.assignees.all %}
                    <div class="d-flex align-items-center mb-3">
                      <div
                          class="avatar avatar-sm rounded-circle bg-gradient-primary me-3">
                        <span
                            class="text-white text-xs">{{ assignee|get_initials }}</span>
                      </div>
                      <div>
                        <h6 class="text-sm mb-1">
                          {{ assignee.first_name }} {{ assignee.last_name }}
                        </h6>
                        <p class="text-xs text-secondary mb-0">
                          {{ assignee.position }}
                        </p>
                      </div>
                    </div>
                  {% empty %}
                    <div class="text-center py-4">
                      <i class="fas fa-users text-secondary opacity-5 mb-3 fa-2x"></i>
                      <p class="text-sm text-secondary mb-0">
                        No assignees yet
                      </p>
                    </div>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/task_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="row mt-4">
    <div class="col-12">
      <div class="card mb-4">
        <div class="card-header pb-0">
          <div class="row align-items-center">
            <div class="col">
              <h5 class="mb-0">
                {{ form.instance.pk|yesno:"Update,Create" }} Task Type
              </h5>
            </div>
            <div class="col text-end">
              <a href="{% url 'tasks:task-type-list' %}" 
                 class="btn btn-sm btn-outline-secondary">
                <i class="fas fa-arrow-left me-2"></i>
                Back to Task Types
              </a>
            </div>
          </div>
        </div>
        <div class="card-body">
          <form method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <br>
              <a href="{% url 'tasks:task-type-list' %}" 
                 class="btn btn-outline-secondary me-2">
                <i class="fas fa-times me-2"></i>
                Cancel
              </a>
              <button type="submit" class="btn bg-gradient-primary">
                <i class="fas fa-save me-2"></i>
                {{ form.instance.pk|yesno:"Update,Create" }} Task Type
              </button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/task_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="row mt-4">
    <div class="col-12">
      <h3 class="mb-3">Task Types</h3>
      <div class="card mb-4">
        <div class="card-header pb-0">
          <div class="row align-items-stretch">
            <div class="col-md-8 d-flex">
              <form method="get" class="d-flex w-100">
                <div class="position-relative w-100">
                  {{ search_form.name|as_crispy_field }}
                </div>
                <button type="submit" class="btn btn-primary ms-2 py-0">
                  Search
                </button>
              </form>
            </div>
            <div class="col-md-4 d-flex justify-content-end align-items-stretch">
              <a href="{% url 'tasks:task-type-create' %}"
                 class="btn btn-sm btn-primary text-center py-2"
                 style="line-height: 1.9; display: inline-block;">
                <i class="fas fa-plus me-2"></i>
                Create Task Type
              </a>
            </div>
          </div>
        </div>
        <div class="card-body px-0 pt-0 pb-2">
          <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
              <thead>
              <tr>
                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 w-100">
                  Task
                </th>
                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                  Update
                </th>
                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                  Delete
                </th>
              </tr>
              </thead>
              <tbody>
              {% for task_type in task_type_list %}
                <tr>
                  <td>
                    <div class="d-flex px-3 py-1">
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="mb-0 text-sm">
                          {{ task_type.name }}
                        </h6>
                      </div>
                    </div>
                  </td>
                  <td class="align-middle text-center text-sm">
                    <div class="d-flex flex-column justify-content-center">
                      <a href="{% url 'tasks:task-type-update' pk=task_type.id %}"
                         class="btn btn-sm btn-outline-primary d-block mx-auto">
                        <i class="fas fa-edit me-2"></i>
                        Update
                      </a>
                    </div>
                  </td>
                  <td class="align-middle text-center text-sm">
                    <div class="d-flex flex-column justify-content-center">
                      <a href="{% url 'tasks:task-type-delete' pk=task_type.id %}"
                         class="btn btn-sm btn-outline-primary d-block mx-auto">
                        <i class="fas fa-trash me-2"></i>
                        Delete
                      </a>
                    </div>
                  </td>
                  {% empty %}
                <tr>
                  <td colspan="5" class="text-center py-4">
                    <p class="text-sm mb-0">No pending task types found</p>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}